export const ADICIONA_PROJETO = 'ADICIONA_PROJETO'
export const ALTERA_PROJETO = 'ALTERA_PROJETO'
export const EXCLUI_PROJETO = 'EXCLUI_PROJETO'
export const DEFINIR_PROJETOS = 'DEFINIR_PROJETOS'

export const NOTIFICAR = 'NOTIFICAR'